# Generated by Django 6.0 on 2026-01-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_core", "0002_course_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_thumbnails/"
            ),
        ),
    ]
